//THIS FILE IS AUTOGENERATED. PLEASE DON'T CHANGE IT!

using ProtoBuf;

namespace AzLn.Protocol.P10
{
    [ProtoContract]
    public class Cs10800 : BaseCommand
    {
        public Cs10800()
        {
            CommandId = 10800;
            FromServer = false;
        }

        [ProtoMember(1, IsRequired = true)]
        public uint State;

        [ProtoMember(2, IsRequired = true)]
        public string Platform;

    }

}
