//THIS FILE IS AUTOGENERATED. PLEASE DON'T CHANGE IT!

using ProtoBuf;

namespace AzLn.Protocol.P10
{
    [ProtoContract]
    public class Sc10801 : BaseCommand
    {
        public Sc10801()
        {
            CommandId = 10801;
            FromServer = true;
        }

        [ProtoMember(1, IsRequired = true)]
        public string GatewayIp;

        [ProtoMember(2, IsRequired = true)]
        public uint GatewayPort;

        [ProtoMember(3, IsRequired = true)]
        public string Url;

        [ProtoMember(4, IsRequired = false)]
        public string[] Version;

        [ProtoMember(5, IsRequired = false)]
        public string ProxyIp;

        [ProtoMember(6, IsRequired = false)]
        public uint ProxyPort;

    }

}
